#!/bin/bash

GPU=GTX480
TIME=60

if [ "$3" == "debug" ]; then
  prun -t $TIME -no-panda -native "-l gpu=$GPU" cuda-gdb 1 --args ./ap -i $1 -n $2
else
  prun -t $TIME -no-panda -native "-l gpu=$GPU" ./ap 1 -i $1 -n $2
fi
