#!/bin/bash

GPU=GTX480

if [ "$3" == "debug" ]; then
  prun -no-panda -t 2:00:00 -native "-l gpu=$GPU" cuda-gdb 1 --args ./ap -i $1 -n $2
else
  prun -no-panda -t 2:00:00 -native "-l gpu=$GPU" ./ap 1 -i $1 -n $2
fi
