#!/bin/sh

if [ $# -ne 3 ]; then
  echo "Usage: $0 [gephi toolkit data file] [C data file] [number of nodes]"
  exit 1
fi

FILENAME=test.data

# Run test.py, printing sum of the x+y differences for each node.
./test.py $1 $2 $3 > $FILENAME
# Plot the difference over iterations.
/usr/bin/gnuplot <<__EOF
set terminal png
set output "plot.png"
plot "$FILENAME" with lines
__EOF

cat $FILENAME

# Remove temporary files.
rm $FILENAME 

