#!/bin/sh

FILENAME=test.data
TMPCDATA=fa2c.data

# Remove the first iteration from the C Force Atlas 2, because it lags behind
# one iteration.
sed "1,$3d" $2 > $TMPCDATA
# Remove empty line.
sed -i '1,1d' $TMPCDATA
 
# Run test.py, printing sum of the x+y differences for each node.
./test.py $1 $TMPCDATA > $FILENAME
# Plot the difference over iterations.
/usr/bin/gnuplot <<__EOF
set terminal png
set output "plot.png"
plot "$FILENAME" with lines
__EOF

# Remove temporary files.
rm $FILENAME $TMPCDATA

